# Generated by Django 5.2 on 2025-11-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinatario', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('RESERVA_CREADA', 'Reserva Creada'), ('RESERVA_CANCELADA', 'Reserva Cancelada'), ('EQUIPO_BLOQUEADO', 'Equipo en Mantenimiento'), ('EQUIPO_DISPONIBLE', 'Equipo Disponible'), ('AFORO_MODIFICADO', 'Aforo Modificado'), ('ALERTA_SISTEMA', 'Alerta del Sistema')], default='ALERTA_SISTEMA', max_length=30),
            preserve_default=False,
        ),
    ]
