# Generated by Django 5.2 on 2025-11-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_inicio']},
        ),
    ]
